version: '3'

networks:
  react_net:
    driver: bridge

services:
  frontend:
    build: ./
    image: react_front
    container_name: frontend
    tty: true
    volumes:
      - ../front:/app
    working_dir: "/app"
    ports:
      - 8000:8000
    networks:
      - react_net

  backend:
    build: ./
    image: node_back
    container_name: backend
    tty: true
    volumes:
      - ../back:/app
    working_dir: "/app"
    ports:
      - 3000:3000
    networks:
      - react_net
  
